config/routes.rb
Rails.application.routes.draw do
 
  
  get "articles/search"
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "user/password",
  }
  resources :categories
 # get 'articles/index'
  get 'welcome/index'
  root "articles#index"

  post "contacts/new"
  get 'welcome/contacto'
  resources :contacts, only: [:create, :new]
  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ApplicationRecord
    include PermissionsConcern
    has_many :comments, dependent: :destroy
    has_many :has_categories, dependent: :destroy
    has_many :categories, through: :has_categories, dependent: :destroy
    after_create :save_categoryMetodo
    belongs_to :user
    validates :title, uniqueness: true
    validates :title,:body, presence: true
    validates :title, length: {in: 5..13 }
    validates :body, length: {minimum: 450, too_short: "Minimo son %{count} caracteres" }
    validate :valide_categories
    scope :ultimos, -> {order("created_at DESC")}
    scope :ult, -> {where(title: "Registro")} 
    scope :titulo, -> (title) { where("lower (title) LIKE ?", "%#{title}%") } 
  #  scope :titulo, -> (find_titulo) {where title: find_titulo}

    has_attached_file :cover,
     styles: {
         thumb: { geometry: '320x240>', format: :png, convert_options: " -background '#A9BCF5' -gravity center -extent 320x240" },
       #  thum: { geometry: '320x240#', format: :png, convert_options: " -background white -gravity center -extent 300x300" },
         medium: { geometry: '800x600', format: :png, convert_options: " -background white -gravity center -extent 800x600" },
         mini: "400x200>",
         big: "500x500>"},
         default_url: "/images/:style/missing.png"
    validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
    
    def categoryMetodo=(value)
        @categories = value
        #raise value.to_yaml
    end
    
    def getCategories
        @categories
    end
    private
    def save_categoryMetodo
            @categories.each do |category_id|
             #  raise "category_id #{category_id} article_id #{self.id}"
                HasCategory.create(category_id: category_id, article_id: self.id )
        end
    end
    def valide_categories
        if self.getCategories.blank? && self.id.nil?
            errors.add(:categories, "Debe agregar una categoria.")
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    #before_action :authenticate_user! , only: [:edit, :update, :destroy, :new, :create]
    before_action :authenticate_editor! , only: [:create, :new, :update, :edit]
    before_action :authenticate_admin! , only: [:destroy]

  def search
    if params.has_key?(:titulo) && params[:titulo].length > 0
      @articles = Article.titulo(params[:titulo])
    else
      @articles = Article.all
    end
  end

  def index
    @articulos = Article.paginate(:page => params[:page], :per_page => 4).ultimos
    if user_signed_in? && current_user.is_editor? && !params.has_key?(:normal)
      render :"admin_article"
    end
  end

  def show
    @comment = Comment.new
    #raise params.to_yaml
  end

def new
  @article = Article.new
    @categories = Category.all
  end

  def create
      @article = current_user.articles.new(article_params)
      @article.categoryMetodo = params[:categories]
      #raise @article.to_yaml
      respond_to do |format|
        if @article.save
          format.html {redirect_to @article, notice: "Articulo #{@article.title}  creado."}
          format.json {render :show, status: :created, location: @article}
        else
          format.html { render :new }
          format.json {render json: @article.errors, status: :unprocessable_entity}
        end
      end
    end
  




  def edit
    
  end

  def update
  #  @article.categoryMetodo = @article.categories.ids
    respond_to do |format|
      if @article.update(article_params)
        format.html {redirect_to @article, notice: "Articulo #{@article.title}  mofificado."}
        format.json {render :show, status: :ok, location: @article}
      else
        format.html {render :edit}
        format.json {render json: @article.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html {redirect_to @article, notice: "Articulo #{@article.title}  eliminado."}
      format.json {head :no_content}
    end 
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :categories, :cover)
  end

  def set_article
    begin
      @article = Article.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, alert:"No existe ese articulo"
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="col-12 col-sm-6 col-md-4 col-lg-3 article-salto">
    <div class="card h-100 article-container ">
        <%= link_to article do %>
            <div style="" class="card-body" >
                <%= image_tag article.cover(:thumb),class:"card-img-top" %>
                <h2 class="card-title text-center h2color" <%= link_to  truncate(article.title, length:15), article %></h2>
                <p><%=truncate_html(article.body.html_safe, length: 120) %></p>
        <%end%>  
                <%temporal = "Categorias: "%>
                <% article.categories.each do |category| %>      
                    <%temporal =   "#{temporal}  #{category.name}"%>
                <%end%>      
                <p> <%= temporal%> </p>   
            </div>
         
    </div> 
</div>

app/views/articles/_formulario.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron space-a">
                <fieldset>
                        <h1 class="text-center space-title form-title"><%= "#{titulo} Articulo" %></h1>
                        <%= form_with(model: article, local: true) do |form| %>
                                <% if article.errors.any? %>
                                <div id="error_explanation">
                                <h5><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h5>
                                <ul>
                                <% article.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                <% end %>
                                </ul>
                                </div>
                            <% end %>
                                <div class="form-group row">
                                    <%= form.label "Titulo:",  class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
                                    <%= form.text_field :title,  class:"col-md-4 form-control" %>
                                </div>
                                
                                <div class="form-group row">
                                    <%= form.label "Banner:",  class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
                                    <%= form.file_field :cover,  class:"col-md-4 form-control" %>
                                </div>    
                            <div class="">
                                <%= form.trix_editor :body, class:"form-control" %>
                            </div>
                            <% Category.all.each do |category| %>
                                <%= check_box_tag "categories[]", category.id%> <%=category.name %><br>
                            <%end%>
                            <div class="form-group row">
                                <div class="container text-center">                
                                    <%= form.submit value="Crear", class:"btn btn-info col-md-3" %>
                                    <%= link_to  "Atras", articles_path, class:"btn btn-info col-md-3" %>
                                </div>
                            </div>       
                        <% end %> 
                </fieldset>
            </div>
        </div>
    </div>
</div>

app/views/articles/admin_article.html.erb
<div class="jumbotron table-responsive">
        <h1>Administrador</h1>
        <p><%= link_to  "Normal", articles_path(normal:true),class:"btn btn-success" %></p>
        <div class="table">
            <table class="table table-bordered">
                <thead class="thead-dark"> 
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Titulo</th>
                        <th scope="col">Autor</th>    
                        <th scope="col">Fecha</th>
                        <th class="text-center">Acciones</th>                  
                    </tr>
                </thead>
                <tbody class="tabla-tbody">
                    <%@articulos.each do |art| %>
                    <tr scope="row" class="tabla-tr text-center">
                        <td><%= art.id %></td>
                        <td><%= art.title %></td>
                        <td><%= art.user.email %></td>
                        <td><%= art.created_at.strftime("%B, %d, %Y, %H:%M")%></td>
                        <td>
                            <%=link_to "ver", art, class:"btn btn-info"%>
                            <%=link_to "Editar", edit_article_path(art),class:"btn btn-warning"%>
                            <%=link_to "Eliminar", art, method: :delete, data:{confirm:"Desea eliminar?"},class:"btn btn-danger"%>
                        </td>    
                    </tr>
                    <%end%>
                </tbody>
            </table>
            <div class="flickr_pagination" style="margin-top: 20px; margin-bottom: 20px;">
                <%= will_paginate @articulos %>  
            </div>
        </div>
    </div>

app/views/articles/edit.html.erb
<%= render "formulario", article: @article, titulo: "Editar" %>

app/views/articles/index.html.erb
<div class="container-fluid">
    <div class="row">
      <%= render @articulos %>
    </div>

  <div class="flickr_pagination" style="margin-top: 20px; margin-bottom: 20px;">
    <%= will_paginate @articulos %>  
  </div>
</div>           

    

app/views/articles/new.html.erb
<%= render "formulario", article: @article, titulo: "Nuevo" %>

app/views/articles/search.html.erb
<div class="jumbotron search-jumbotron">
    <div class="row search-body">
        <% if ! @articles.blank? %>
            <% @articles.each do |art| %>
                <div class="col-md-6 search-fondo search-body">
                    <div class="">
                        <h1><%= link_to  art.title, art, class:"search-title" %></h1>
                        <p class=""><%= truncate_html(art.body, length:200) %></p>
                        <p class="text-right"><%= link_to  "Ver mas", art, class:"btn btn-success" %></p>  
                    </div>
                </div>
            <%end%>        
        <%else%>
            <div class="col-md-10 offset-md-1">        
                <h1 class="text-center">Lo siento...</h1>
                <p class="text-center">No se encuentran concidencias con <%="\"#{params[:titulo]}\""%></p>
            </div>
        <%end%>           
    </div>
</div>

app/views/articles/show.html.erb
<div class="jumbotron" style="padding-top: 15px "> 
    <h1 class="text-center"><%=@article.title%></h1>

    <% if user_signed_in? && current_user.is_editor? %>
        <div class="row">
            <div class="col-12 col-md-4 offset-md-4">
                <%= link_to  "Editar", edit_article_path(@article), class:"btn btn-warning btn-block" %>
            </div>
        </div>
    <%end%>

    <div class="article-html ">
        <div class="row">  
            <div class="col-md-8 offset-md-2">  
                <div class="text-center">         
                    <%= image_tag @article.cover(:big), class:"img-fluid" %>
                </div>     
            </div>        
        </div>


        <div class="row ">  
            <div class="col-md-8 offset-md-2 col-12 text-justify ">
                <% if !@article.user.nil? %>
                    <p><%=@article.user.email%></p>
                <%end%>

                <% @article.categories.each do |category| %>
                    <span class="badge badge-primary"> <%= link_to category.name, category, style:"color:#fff; font-size: 17px" %> </span>       
                <%end%>    
                
                <%=@article.body.html_safe%>  
                <% if user_signed_in? %>
                <%= render "comments/form", comment: @comment%>
                <%end%>
                <ul class="list-group list-group-flush text-capitalize">
                    <% @article.comments.each do |comment| %>
                        <li class="list-group-item active mt-1">
                            <div class="row">
                                <div class="col-md-6">
                                    <%= comment.user.email%>: <%= comment.body %>
                                </div>
                                <div class="col-md-6">
                                    <% if user_signed_in? && current_user == comment.user %>
                                        <%= link_to "Editar", edit_article_comment_url(@article,  comment), class:"btn btn btn-warning text-white" %>
                                        <%= link_to "Eliminar", [@article, comment], data:{ confirm: '¿Estas seguro?', 
                                            method: :delete}, class:"btn btn btn-danger text-white" %>
                                    <% end %>
                                </div>
                            </div>
                        </li>
                    <%end%>
                </ul>        
            </div>  
        </div>
    </div>  
     <%= link_to  "Atras", root_path, class:"btn btn-info" %>
</div>