config/routes.rb
Rails.application.routes.draw do
 
  
  get "articles/search"
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "user/password",
  }
  resources :categories
 # get 'articles/index'
  get 'welcome/index'
  root "articles#index"

  post "contacts/new"
  get 'welcome/contacto'
  resources :contacts, only: [:create, :new]
  resources :articles do
    resources :comments
  end

end

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation" style="">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to  "Inicio", root_path, class:"nav-link"%> 
        <li class="nav-item">
          <%= link_to  "Contacto", new_contact_path, class:"nav-link"%> 
        </li>
        <%if user_signed_in?%>
          <%= link_to  "Cerrar sesion", destroy_user_session_path, method: :delete,  class:"nav-link" %>
          <%else%>
            <%= link_to  "Iniciar sesion", user_session_path,  class:"nav-link" %>
            <%= link_to  "Registrar ", new_user_registration_path,  class:"nav-link" %>  
        <%end%>

      </ul>


    <%= form_tag articles_search_path, :method => 'get',class:"form-inline my-2 my-lg-0" do %>
    
      <%= text_field_tag :titulo, params[:titulo],class:"form-control mr-sm-2" %>
      <%= submit_tag "Search", :name => nil, class:"btn btn-secondary my-2 my-sm-0" %>
    
    <% end %>
  </div>
</nav> 

app/views/partials/_notificaciones.html.erb
<% if !notice.nil?%>
  
    <div class="alert alert-dismissible alert-primary ">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%=notice%>
    </div>
<%end%>    
<% if !alert.nil?%>
    <div class="alert alert-dismissible alert-warning padding-Alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h4 class="alert-heading">Warning!</h4>
                <p><%=alert%></p>
    </div>
<%end%>    

app/views/partials/_panel.html.erb
<% if user_signed_in? %>  
  <% if current_user.is_editor? %>
    <div class="list-group">
      <%= link_to  "Administrador", root_path, class:"list-group-item list-group-item-action active " %>
      <%= link_to  "ver Articulos", articles_path, class:"list-group-item list-group-item-action " %>
      <%= link_to  "Crear articulo", new_article_path, class:"list-group-item list-group-item-action " %>
      <%= link_to  "Ver categorias", categories_path, class:"list-group-item list-group-item-action " %>
      <%= link_to  "Crear categorias", new_category_path, class:"list-group-item list-group-item-action " %>
    </div>
  <%end%>  
<%end%>  

<div class="list-group">
  <%= link_to  "Categorias", categories_path, class:"list-group-item list-group-item-action active" %>
  <% @categorias.each do |categoria| %>
    <%= link_to  categoria.name, categoria , class:"list-group-item list-group-item-action" %>
  <%end%>
</div> 