config/routes.rb
Rails.application.routes.draw do
 
  
  get "articles/search"
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "user/password",
  }
  resources :categories
 # get 'articles/index'
  get 'welcome/index'
  root "articles#index"

  post "contacts/new"
  get 'welcome/contacto'
  resources :contacts, only: [:create, :new]
  resources :articles do
    resources :comments
  end

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :has_categories, dependent: :destroy
    has_many :articles, through: :has_categories, dependent: :destroy

    belongs_to :user
    validates :name,:color, presence: true
    validates :name, length: {in: 7..20 }
    validates :name, length: {in: 4..10 }

    has_attached_file :coverCat,
     styles: {
         thumb: { geometry: '320x240>', format: :png, convert_options: " -background '#A9BCF5' -gravity center -extent 320x240" },
       #  thum: { geometry: '320x240#', format: :png, convert_options: " -background white -gravity center -extent 300x300" },
         medium: { geometry: '800x600', format: :png, convert_options: " -background white -gravity center -extent 800x600" },
         mini: "400x200>",
         big: "500x500>"},
         default_url: "/images/:style/missing.png"
    validates_attachment_content_type :coverCat, content_type: /\Aimage\/.*\Z/
    
   


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user! , only: [:edit, :update, :destroy, :new, :create]
  before_action :authenticate_editor! , only: [:create, :new, :update, :edit]
  before_action :authenticate_admin! , only: [:destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    if user_signed_in? && current_user.is_editor? && !params.has_key?(:normal)
      render :"admin_category"
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @articles = @category.articles.paginate(:page => params[:page], :per_page => 2) 
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = current_user.categories.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      begin
        @category = Category.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to root_path, alert:"No existe esa categoria"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :color, :coverCat)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<style type="text/css" media="screen">
    <%= ".#{category.name.delete(' ')}" %>{
      background: <%= category.color %> !important;
    }
  </style>
 
 <div class="col-md-3 ">
    <div class="card">
        <div class="categories-container">
            <%= link_to category do %>
                <div class="card-body <%="#{category.name.delete(' ')}"%> ">
                    <h2 class="card-title text-center"><%= category.name %></h2>
                        <%= image_tag category.coverCat(:thumb),class:"card-img-top" %>
                    <p>
                        <%= "Contiene #{category.articles.count} articulo(s)" %>
                    </p>
                    <div class"card-text">
                        <%="Creado en #{category.created_at.strftime("%b, %d, %Y, %H:%M") }"%>
                    </div>
                </div>
            <%end%>
        </div>
    </div>
 </div>

app/views/categories/_form.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="jumbotron space-a">
                <fieldset>
                  <h1 class="text-center space-title form-title"><%="#{title} Categoria"%></h1>
                  <%= form_with(model: category, local: true) do |form| %>
                    <% if category.errors.any? %>
                      <div id="error_explanation">
                        <h5><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h5>
                        <ul>
                        <% category.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="form-group row">
                      <%= form.label :name,  class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
                      <%= form.text_field :name, id: :category_name,  class:"col-md-4 form-control" %>
                    </div>
                    
                    <div class="form-group row">
                        <%= form.label "Banner:",  class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
                        <%= form.file_field :coverCat,  class:"col-md-4 form-control" %>
                    </div>    

                    <div class="form-group row">
                      <%= form.label :color,  class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
                      <%= form.color_field :color, id: :category_color,  class:"col-md-4 form-control" %>
                    </div>
 

                    <div class="form-group row">
                        <div class="container text-center">                
                            <%= form.submit value="Crear", class:"btn btn-info col-md-3" %>
                            <%= link_to  "Atras", categories_path, class:"btn btn-info col-md-3" %>
                        </div>
                    </div>       
                  <% end %>       

                </fieldset>
              </div>
          </div>
      </div>
  </div>
  
  

app/views/categories/admin_category.html.erb
<div class="jumbotron">
    <h1>Administrador</h1>
    <p><%= link_to  "Normal", categories_path(normal:true),class:"btn btn-success" %></p>
    <table class="table table-bordered">
        <thead class="thead-dark"> 
            <tr>
                <th class="text-center">Titulo</th>
                <th class="text-center">Ver Editar Eliminar</th>                  
            </tr>
        </thead>
        <tbody class="tabla-tbody">
            <%@categories.each do |cat| %>
            <tr class="tabla-tr text-center">
                <td><%="#{cat.name} #{cat.created_at.strftime("%b, %d, %Y, %H:%M") }"%></td>
                <td>
                    <%=link_to "ver", cat,class:"btn btn-info"%>
                    <%=link_to "Editar", edit_category_path(cat),class:"btn btn-warning"%>
                    <%=link_to "Eliminar", cat, method: :delete, data:{confirm:"Desea eliminar?"},class:"btn btn-danger"%>
                </td>    
            </tr>
            <%end%>
        </tbody>
    </table>
</div>

app/views/categories/edit.html.erb
<%= render 'form', category: @category, title:"Editar" %>

app/views/categories/index.html.erb
<div class="row">
  <%= render @categories %>
</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category, title: "Nueva" %>

app/views/categories/show.html.erb
<style type="text/css" media="screen">
  .jumbotron{
    margin-top: 5px !important;

  }

  .categories-show{
        background: <%=@category.color%> !important;
  }
</style>

<div class="categories-show">
  
      <h1 class="text-center"> <%= @category.name %>  </h1>
      <h5 class="text-center ">
          <% if !@category.user.nil? %>
            Creado por <strong><%= @category.user.email%></strong>
          <%end%>
      </h5>
</div>

<div class="row " >
  <%= render @articles %>   
</div>

<div class="flickr_pagination" style="margin-top: 20px; margin-bottom: 20px;">
    <%= will_paginate @articles %>  
</div>